[package]
name = "nemesis-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
nemesis-protocol = { path = "../nemesis-protocol" }
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
